name = "soundmaster-semantic-search"
main = "index.js"
compatibility_date = "2024-01-01"

[vars]
SUPABASE_URL = "https://tclqqvbpdqefpjqbdfle.supabase.co"

# The following secrets need to be set using `wrangler secret put`:
# - SUPABASE_ANON_KEY