// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fyfrrrwmrjgqbvseqqje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5ZnJycndtcmpncWJ2c2VxcWplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1Mjc1NDgsImV4cCI6MjA1NDEwMzU0OH0.h6_Z-KYyD-F-mPvkICpdnLeSw-xr4Xe_5C1JQMetMkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);